CC=gcc
FLAGS= -Wall

all: cp cat readln readln_v2 nl 

cp:
	$(CC) $(FLAGS) -o cp cp.c

cat: 
	$(CC) $(FLAGS) -o cat cat.c

readln:
	$(CC) $(FlAGS) -o readln readln.c

readln_v2:
	$(CC) $(FLAGS) -o readln_v2 readln_v2.c

nl:
	$(CC) $(FLAGS) -o nl nl.c

clean:
	rm cp cat readln nl person

