/*
 * This file was automatically generated by EvoSuite
 * Sun Dec 20 18:51:03 GMT 2020
 */

package model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.beans.PropertyChangeEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Set;
import model.Loja;
import model.SistemaGestaoVendas;
import model.Transportadora;
import model.Utilizador;
import model.Voluntario;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SistemaGestaoVendas_ESTest extends SistemaGestaoVendas_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      PropertyChangeEvent propertyChangeEvent0 = new PropertyChangeEvent("Nao ha compras registadas", (String) null, "Nao ha compras registadas", "Nao ha compras registadas");
      // Undeclared exception!
      try { 
        sistemaGestaoVendas0.propertyChange(propertyChangeEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      // Undeclared exception!
      try { 
        SistemaGestaoVendas.fromLogFile((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.shouldAllThrowIOExceptions();
      FileSystemHandling.appendStringToFile(evoSuiteFile0, ", transportadoras=");
      try { 
        SistemaGestaoVendas.fromLogFile("d");
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      try { 
        SistemaGestaoVendas.fromLogFile("smQ");
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      String string0 = sistemaGestaoVendas0.top10Transportadoras();
      assertEquals("Nao ha compras registadas", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      String string0 = sistemaGestaoVendas0.top10Utilizadores();
      assertEquals("Nao ha compras registadas", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      Loja loja0 = new Loja();
      Boolean boolean0 = new Boolean(true);
      PropertyChangeEvent propertyChangeEvent0 = new PropertyChangeEvent(loja0, "transportadora_set_disponibilidade", boolean0, "transportadora_set_disponibilidade");
      // Undeclared exception!
      try { 
        sistemaGestaoVendas0.propertyChange(propertyChangeEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // model.Loja cannot be cast to controller.TransportadoraLogin
         //
         verifyException("model.SistemaGestaoVendas", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      Utilizador utilizador0 = new Utilizador();
      PropertyChangeEvent propertyChangeEvent0 = new PropertyChangeEvent(utilizador0, "Nao ha compras registadas", sistemaGestaoVendas0, (Object) null);
      sistemaGestaoVendas0.propertyChange(propertyChangeEvent0);
      assertEquals("Nao ha compras registadas", propertyChangeEvent0.getPropertyName());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      Transportadora transportadora0 = sistemaGestaoVendas0.getSpecificTransportadora("Nao ha compras registadas");
      assertNull(transportadora0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      Utilizador utilizador0 = sistemaGestaoVendas0.getSpecificUtilizador("d");
      assertNull(utilizador0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      Loja loja0 = sistemaGestaoVendas0.getSpecificLoja("Dados de LOGS:");
      assertNull(loja0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      Voluntario voluntario0 = sistemaGestaoVendas0.getSpecificVoluntario("Dados de LOGS:");
      assertNull(voluntario0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "D<ado,[d7 WGS:");
      // Undeclared exception!
      try { 
        SistemaGestaoVendas.fromLogFile("d");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      Set<Voluntario> set0 = sistemaGestaoVendas0.getVoluntarios();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      Set<Transportadora> set0 = sistemaGestaoVendas0.getTransportadoras();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      Set<Loja> set0 = sistemaGestaoVendas0.getLojas();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      Set<Transportadora> set0 = sistemaGestaoVendas0.getTransportadorasDisponiveis();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      Set<Utilizador> set0 = sistemaGestaoVendas0.getUtilizadores();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("d");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "Dados de LOGS:");
      SistemaGestaoVendas sistemaGestaoVendas0 = SistemaGestaoVendas.fromLogFile("d");
      String string0 = sistemaGestaoVendas0.toString();
      assertEquals("SistemaGestaoVendas{voluntarios=[], utilizadores=[], transportadoras=[], lojas=[], encomendas=[]}", string0);
  }
}
