all : ex1 ex2 ex3 ex4 ex5 

ex1 : 
	gcc -o ex1 ex1.c

ex2 : 
	gcc -o ex2 ex2.c 

ex3 : 
	gcc -o ex3 ex3.c

ex4 :
	gcc -o ex4 ex4.c

ex5 :
	gcc -o ex5 ex5.c

ex5v2 :
	gcc -o ex5v2 ex5v2.c

clean :
	rm -f ex1 ex2 ex3 ex4 ex5 ex5v2
