CC = gcc

all : ex1 ex2 ex3 ex4 ex5 ex6 ex7

ex1 :
	$(CC) -o ex1 ex1.c
	
ex2 :
	$(CC) -o ex2 ex2.c

ex3 : 
	$(CC) -o ex3 ex3.c

ex4 : 
	$(CC) -o ex4 ex4.c

ex5 : 
	$(CC) -o ex5 ex5.c

ex6 :
	$(CC) -o ex6 ex6.c

ex7 : 
	$(CC) -o ex7 ex7.c

clean :
	  rm -f ex1 ex2 ex3 ex4 ex5 ex6 ex7
