all : ex1 ex2 ex3 ex4 exa1 

ex1 : 
	gcc -o ex1 ex1.c readln.c

ex2 :
	gcc -o ex2 ex2.c readln.c

ex3 : 
	gcc -o ex3 ex3.c

ex4 :
	gcc -o ex4 ex4.c

exa1 :
	gcc -o exa1 exa1.c

bash : 
	gcc -g -o bash bash.c readln.c

clean : 
	rm -f ex1 ex2 ex3 ex4 exa1 erros.txt saida.txt
