- name: Create private group for minio user
  group:
    name: minio
    state: present

- name: Create minio user
  user:
    name: minio
    group: minio
    system: yes
    shell: "/bin/bash"

- name: Create the Minio data storage directories
  file:
    path: "/opt/minio/data"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Generate the Minio server envfile
  template:
    src: minio.env
    dest: "/etc/default/minio"
    owner: "root"
    group: "root"
    mode: 0640
  notify: restart_minio

- name: Check for existing binary
  stat:
    path: "/usr/local/bin/minio"
  register: minio_binary_stat_result

- name: Download minio server
  get_url:
    url: "https://dl.minio.io/server/minio/release/linux-amd64/minio"
    dest: "/tmp"
    mode: 0755
  when: not minio_binary_stat_result.stat.exists

- name: Install minio binary
  copy:
    src: "/tmp/minio"
    dest: "/usr/local/bin/minio"
    owner: "root"
    group: "root"
    mode: 0755
    remote_src: true
  when: not minio_binary_stat_result.stat.exists
  notify: restart_minio

- name: Copy systemd unit file
  template:
    src: "../templates/minio.service"
    dest: "/etc/systemd/system/minio.service"
    owner: root
    group: root
    mode:
  register: minio_service_results
  notify:
    - reload minio systemd
    - restart_minio

- name: Enable minio service
  service:
    name: minio
    state: started
    enabled: true
