# This file allows you to run mattermost within your docker swarm mode cluster
# for more informations check: https://docs.docker.com/engine/swarm/
#
# Simply run:
#
# `docker stack up [STACK NAME] -c docker-stack.yml`
#
# In this case `mattermost` is going to be stack name, so the command will be:
#
# `docker stack up mattermost -c docker-stack.yml`
#
# From now on all the services that belong to this stack will be prefixed with `mattermost_`
# this file defines 3 services, these are going to be mattermost_db, mattermost_app and mattermost_web,
# each of these names is the service's hostname as well, they can communicate
# with each other easily by using the hostname instead of the ip or exposing ports to the host.
#
# As a side note, images tagged as latest are pulled by default,
# that means there's no need to use `image:latest`
#
# use latest compose v3.3 file format for optimal compatibility with latest docker release and swarm features.
# see https://docs.docker.com/compose/compose-file/compose-versioning/#version-3
# and https://docs.docker.com/compose/compose-file/compose-versioning/#version-33
# and https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading

version: '3.3'
networks:
  # network for App <-> DB transactions
  mm-in:
    driver: overlay
    internal: true
  # this network faces the outside world
  mm-out:
    driver: overlay
    internal: false
volumes:
  mm-dbdata:
services:
  app:
    # use official mattermost prod-app image
    image: mattermost/mattermost-prod-app:5.13.0
    networks:
      - mm-in
      - mm-out
    volumes:
      - /var/lib/mattermost/config:/mattermost/config:rw
      - /var/lib/mattermost/data:/mattermost/data:rw
      - /var/lib/mattermost/logs:/mattermost/logs:rw
      - /var/lib/mattermost/plugins:/mattermost/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # use service's hostname
      - DB_HOST=10.132.0.54
      # talk to the port within the overlay network
      # without (over)exposing ports
      - DB_PORT_NUMBER={{ mm_db_port }}
      - MM_USERNAME={{ mm_db_user }}
      - MM_PASSWORD={{ mm_db_password }}
      - MM_DBNAME={{ mm_db_name }}
      - MM_SQLSETTINGS_DRIVERNAME={{ mm_db_driver }}
      - MM_SQLSETTINGS_DATASOURCE={{ mm_db_user }}:{{ mm_db_password }}@tcp(10.132.0.26:{{ mm_db_port }})/{{ mm_db_name }}?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s

      # pass the edition to be used, default is enterprise
      # setting this env var will make the app use the team edition
      - edition=team
      # in case your config is not in default location
      # - MM_CONFIG=/mattermost/config/config.json
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 2  